### 00) signup -create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Hanna Virtanen",
    "role": "admin",
    "password": "sala125"
}

### 0) login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "Hanna Virtanen",
    "password": "sala125"
}

### 1.1) get all patients
GET http://localhost:3000/patient
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Ikhhbm5hIFZpcnRhbmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1ODc0MDcwLCJleHAiOjE3NjU4Nzc2NzB9._eVwDzyCGtX42nIISL2ymaRmNrmUZrgjALrEz6PisFg

### 1.2) get patients, filtered by name
GET http://localhost:3000/patient?name=onni makinen
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Ikhhbm5hIFZpcnRhbmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1ODc0MDcwLCJleHAiOjE3NjU4Nzc2NzB9._eVwDzyCGtX42nIISL2ymaRmNrmUZrgjALrEz6PisFg

### 1.3) get patients, filtered by department
GET http://localhost:3000/patient?department=carDiology
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6Ik9ubmkgVmlydGFuZW4iLCJyb2xlIjoicmVndWxhciIsImlhdCI6MTc2NTg3Mzg1MiwiZXhwIjoxNzY1ODc3NDUyfQ.TGo9QZWOtZFkeiYfC6Df77_xC04VsRieHFDtCupTPfI

### 1.4) get patients, filtered by diagnosis
GET http://localhost:3000/patient?diagnosis=Diathesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywibmFtZSI6Ik9ubmkgVmlydGFuZW4iLCJyb2xlIjoicmVndWxhciIsImlhdCI6MTc2NTg3Mzg1MiwiZXhwIjoxNzY1ODc3NDUyfQ.TGo9QZWOtZFkeiYfC6Df77_xC04VsRieHFDtCupTPfI


### 1.5) get patients, filtered by date of acceptance
GET http://localhost:3000/patient?toDate=2025-12-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Ikhhbm5hIFZpcnRhbmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1ODc0MDcwLCJleHAiOjE3NjU4Nzc2NzB9._eVwDzyCGtX42nIISL2ymaRmNrmUZrgjALrEz6PisFg


### 2) get patient with id 2
GET http://localhost:3000/patient/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Ikhhbm5hIFZpcnRhbmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1ODc0MDcwLCJleHAiOjE3NjU4Nzc2NzB9._eVwDzyCGtX42nIISL2ymaRmNrmUZrgjALrEz6PisFg

### 3) add new patient
POST http://localhost:3000/patient
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Ikhhbm5hIFZpcnRhbmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1ODc0MDcwLCJleHAiOjE3NjU4Nzc2NzB9._eVwDzyCGtX42nIISL2ymaRmNrmUZrgjALrEz6PisFg
Content-Type: application/json

{
    //"name": "Anna Lee",
    //"age": 88,
    "department": "neurology",
    //"diagnosis": "Heart Stroke",
    "accepted": "2025-12-15"

}

### 4) update patient
PUT http://localhost:3000/patient/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Ikhhbm5hIFZpcnRhbmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1ODc0MDcwLCJleHAiOjE3NjU4Nzc2NzB9._eVwDzyCGtX42nIISL2ymaRmNrmUZrgjALrEz6PisFg
Content-Type: application/json

{
    "name": "Helena Cristensen",
    "age": 99,
    "department": "cardiology",
    "diagnosis": "Heart",
    "accepted": "2025-12-14"

}

### 5) delete patient by id
DELETE http://localhost:3000/patient/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6Ikhhbm5hIFZpcnRhbmVuIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNzY1ODc0MDcwLCJleHAiOjE3NjU4Nzc2NzB9._eVwDzyCGtX42nIISL2ymaRmNrmUZrgjALrEz6PisFg
