### 00) signup -create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "name": "Pekka Virtanen",
    "role": "regular",
    "password": "sala126"
}

### 0) login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name": "Pekka Virtanen",
    "password": "sala126"
}

### 1.1) get all patients
GET http://localhost:3000/patient
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU

### 1.2) get patients, filtered by name
GET http://localhost:3000/patient?name=Pekka suolainen
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU

### 1.3) get patients, filtered by department
GET http://localhost:3000/patient?department=carDiology
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU

### 1.4) get patients, filtered by diagnosis
GET http://localhost:3000/patient?diagnosis=Diathesis
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU


### 1.5) get patients, filtered by date of acceptance
GET http://localhost:3000/patient?toDate=2025-12-01
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU


### 2) get patient with id 2
GET http://localhost:3000/patient/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU

### 3) add new patient
POST http://localhost:3000/patient
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU
Content-Type: application/json

{
    "name": "Anna Lee",
    "age": 88,
    "department": "neurology",
    "diagnosis": "Heart Stroke",
    "accepted": "2025-12-16"

}

### 4) update patient
PUT http://localhost:3000/patient/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU
Content-Type: application/json

{
    "name": "Helena Cristensen",
    "age": 99,
    "department": "cardiology",
    "diagnosis": "Heart",
    "accepted": "2025-12-14"

}

### 5) delete patient by id
DELETE http://localhost:3000/patient/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwibmFtZSI6IlBla2thIFZpcnRhbmVuIiwicm9sZSI6InJlZ3VsYXIiLCJpYXQiOjE3NjU4Nzg1NjIsImV4cCI6MTc2NTg4MjE2Mn0.Ffa_LC7Y_3zASi0oSL9gTejgwkDFXvLfTOdRxq0BtOU
